[project]
site_name = "exaStamp"
repo_url = "https://github.com/Collab4exaNBody/exaStamp"
repo_name = "Collab4exaNBody/exaStamp"
copyright = "Copyright &copy; 2025 P. Lafourcade, T. Carrard"
use_directory_urls = false
nav = [
    {"Home" = "index.md"},
    {"Overview" = [
        "Overview/overview.md",
		{"Distribution" = "Overview/distribution.md"},
		{"Code evolution" = "Overview/releases.md"},
		{"Features" = "Overview/features.md"}
    ]},
    {"Build & Install" = [
    	"BuildInstall/index.md",
		"BuildInstall/spack_installation.md",
		"BuildInstall/cmake_installation.md",
		"BuildInstall/running.md"
    ]},
    {"User Guide" = [
    	"User/A_index.md",
		{"Getting Started" = [
            "User/B_GettingStarted/building_blocks.md",
            "User/B_GettingStarted/configuration_files.md",
            "User/B_GettingStarted/yaml_basics.md"
        ]},
        {"Simulation Starter Pack" = [
            "User/C_StarterPack/0_index.md",            
            "User/C_StarterPack/1_global.md",   
            "User/C_StarterPack/2_species.md", 
            "User/C_StarterPack/3_domain.md", 
            "User/C_StarterPack/4_input.md", 
            "User/C_StarterPack/5_force.md", 
            "User/C_StarterPack/6_dump.md",
            "User/C_StarterPack/7_example.md",                                
        ]},
        {"Domain & Regions" = [
            "User/D_DomainRegions/domain.md",
            "User/D_DomainRegions/regions.md"
        ]},
        {"Grids Features" = [
            "User/E_Grids/flavors.md",
            "User/E_Grids/input.md",
            "User/E_Grids/output.md",            
            "User/E_Grids/analysis.md"
        ]},
        {"Particles Features" = [
            "User/F_Particles/species.md",
            "User/F_Particles/input.md",
            "User/F_Particles/output.md",            
            "User/F_Particles/analysis.md",
        ]},
        {"Interatomic Potentials" =  [
            "User/G_ForceFields/index.md",
            "User/G_ForceFields/general.md",
            {"Pair Potentials" = [
                "User/G_ForceFields/Pair/index.md",
                "User/G_ForceFields/Pair/Strategies/index.md",
                {"Styles" = [
                    "User/G_ForceFields/Pair/Models/index.md",
                    "User/G_ForceFields/Pair/Models/buckingham.md",
                    "User/G_ForceFields/Pair/Models/coul_cut.md",
                    "User/G_ForceFields/Pair/Models/coul_wolf_pair.md",
                    "User/G_ForceFields/Pair/Models/exp6.md",    
                    "User/G_ForceFields/Pair/Models/exp6rf.md",
                    "User/G_ForceFields/Pair/Models/lj.md",
                    "User/G_ForceFields/Pair/Models/ljexp6rf_exp6.md",
                    "User/G_ForceFields/Pair/Models/ljexp6rf_lj.md",
                    "User/G_ForceFields/Pair/Models/ljrf.md",
                    "User/G_ForceFields/Pair/Models/ljwolf.md",
                    "User/G_ForceFields/Pair/Models/reaction_field.md",
                    "User/G_ForceFields/Pair/Models/relax.md",
                    "User/G_ForceFields/Pair/Models/tabpair.md",
                    "User/G_ForceFields/Pair/Models/zbl.md",
                    "User/G_ForceFields/Pair/Models/zero.md"                                   
                ]}
            ]},
            {"EAM Potentials" = [
                "User/G_ForceFields/EAM/index.md",
                "User/G_ForceFields/EAM/alloy.md",
                "User/G_ForceFields/EAM/johnson.md",
                "User/G_ForceFields/EAM/ravelo.md",
                "User/G_ForceFields/EAM/sutton_chen.md",
                "User/G_ForceFields/EAM/vniitf.md",
                "User/G_ForceFields/EAM/tab.md",
            ]},
            {"MEAM Potentials" = [
                "User/G_ForceFields/MEAM/meam.md",
                "User/G_ForceFields/MEAM/meam_lj.md",
            ]},
            {"Reactive Potentials" = [
                "User/G_ForceFields/Reactive/lchbop.md",
                "User/G_ForceFields/Reactive/rebo.md",
            ]},
            {"Machine Learning Potentials" = [
                "User/G_ForceFields/MLIP/snap.md",
                "User/G_ForceFields/MLIP/nnp.md",
                "User/G_ForceFields/MLIP/ace.md",
            ]},                 
            {"Electrostatics Potentials" = [
                "User/G_ForceFields/Electrostatics/short.md",
                "User/G_ForceFields/Electrostatics/long.md",
            ]},    
            {"Intramolecular Potentials" = [
                "User/G_ForceFields/Intramolecular/bonds.md",
                "User/G_ForceFields/Intramolecular/torsions.md",
                "User/G_ForceFields/Intramolecular/dihedrals.md",
                "User/G_ForceFields/Intramolecular/impropers.md",                                
            ]},                                                                 
        ]}
#        {"Ensemble & Constraints" = "User/EnsemblesConstraints/index.md"}
		  
    ]},
    {"Tutorials" = [
    		   "Tutorials/index.md",
		   "Tutorials/tutorial1.md",
		   "Tutorials/tutorial2.md",
		   "Tutorials/tutorial3.md",		   
		   ]},
    {"microStamp MiniApp" = ["microStamp/index.md",
			     "microStamp/cmake_installation.md",
			     "microStamp/spack_installation.md",
			     "microStamp/running.md"]},
    {"References" = ["References/index.md",
		     "References/contributions.md"]},
    {"About" = "About/index.md"} 
			
			 
]

extra_javascript = [
    "javascripts/katex.js",
    "https://unpkg.com/katex@0/dist/katex.min.js",
    "https://unpkg.com/katex@0/dist/contrib/auto-render.min.js",
    "javascripts/mathjax.js",
    "https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js"
]

extra_css = [
    "https://unpkg.com/katex@0/dist/katex.min.css",
    "styles/extra_styles.css"
#    "styles/extra.css"
]

[project.theme]
features = [
    "annoce.dismiss",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.tooltips",
    "content.footnote.tooltips",
    "search.highlight",
    "navigation.footer",
    "navigation.top",
    "navigation.tabs",
    "navigation.tabs.sticky",
    "navigation.tracking",
    "navigation.sections"
#    "navigation.indexes"
]
logo = "img/xsp_logo.png"

# Palette toggle for automatic mode
[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

# Palette toggle for light mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
primary = "pink"
accent = "deep purple"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

# Palette toggle for dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
primary = "indigo"
accent = "teal"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

[project.theme.icon]
repo = "fontawesome/brands/github"
previous = "fontawesome/brands/git-alt"
next = "fontawesome/solid/angle-right"
edit = "material/pencil"
view = "material/eye"

[project.markdown_extensions.attr_list]
[project.markdown_extensions.admonition]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.tables]

[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" }
]

[project.markdown_extensions.pymdownx.emoji]
emoji_index = "zensical.extensions.emoji.twemoji" 
emoji_generator = "zensical.extensions.emoji.to_svg"

[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true

[project.markdown_extensions.abbr]

[project.markdown_extensions.pymdownx.inlinehilite]

[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
use_pygments = true
pygments_lang_class = true

[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true

[project.markdown_extensions.pymdownx.arithmatex]
generic = true

[project.markdown_extensions.md_in_html]
[project.markdown_extensions.footnotes]
[project.markdown_extensions.def_list]

[project.markdown_extensions.toc]
toc_depth = 6
permalink = true